apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: monitoring-aws-yjeee-com-tls
  namespace: monitoring
spec:
  secretName: monitoring-aws-yjeee-com-tls
  duration: 2160h      # 90d
  renewBefore: 360h    # 15d
  issuerRef:
    name: my-issuer
    kind: ClusterIssuer
  dnsNames:
  - prometheus.aws-yjeee.com
  - grafana.aws-yjeee.com